export const products = [
  // === 🍿 Food (음식) ===
  {
    id: 101,
    type: "food",
    name: "오리지널 팝콘 (L)",
    price: 6000,
    image: "",
    description: "바삭하고 고소한 맛이 일품인 영화관의 클래식, 오리지널 팝콘입니다.",
  },
  {
    id: 102,
    type: "food",
    name: "카라멜 팝콘 (L)",
    price: 7000,
    image: "",
    description: "달콤한 카라멜이 코팅되어 멈출 수 없는 중독적인 맛의 팝콘입니다.",
  },
  {
    id: 103,
    type: "food",
    name: "치즈 팝콘 (L)",
    price: 7000,
    image: "",
    description: "짭짤한 시즈닝이 가득 뿌려진 단짠의 정석, 체다치즈 팝콘입니다.",
  },
  {
    id: 104,
    type: "food",
    name: "나초 치즈 콤보",
    price: 6500,
    image: "",
    description: "바삭한 나초와 따뜻하고 고소한 치즈 소스의 환상적인 조합입니다.",
  },
  {
    id: 105,
    type: "food",
    name: "칠리치즈 핫도그",
    price: 5500,
    image: "",
    description: "출출함을 달래줄 매콤한 칠리소스와 치즈가 듬뿍 올라간 핫도그입니다.",
  },
  {
    id: 106,
    type: "food",
    name: "버터구이 오징어",
    price: 5000,
    image: "",
    description: "달콤한 버터향이 가득, 쫄깃한 식감의 버터구이 오징어입니다.",
  },
  {
    id: 107,
    type: "food",
    name: "프레첼 (크림치즈)",
    price: 4500,
    image: "",
    description: "따뜻한 프레첼 속에 부드러운 크림치즈가 가득 들어있습니다.",
  },

  // === 🥤 Drink (음료) ===
  {
    id: 201,
    type: "drink",
    name: "콜라 (L)",
    price: 3500,
    image: "",
    description: "톡 쏘는 시원함으로 영화의 즐거움을 더해주는 콜라입니다.",
  },
  {
    id: 202,
    type: "drink",
    name: "제로 콜라 (L)",
    price: 3500,
    image: "",
    description: "칼로리 걱정 없이 즐기는 시원하고 짜릿한 제로 콜라입니다.",
  },
  {
    id: 203,
    type: "drink",
    name: "사이다 (L)",
    price: 3500,
    image: "",
    description: "청량하고 상쾌한 맛의 사이다로 갈증을 해소하세요.",
  },
  {
    id: 204,
    type: "drink",
    name: "오렌지 에이드",
    price: 5000,
    image: "",
    description: "상큼한 오렌지가 그대로 들어간 시원하고 달콤한 에이드입니다.",
  },
  {
    id: 205,
    type: "drink",
    name: "아메리카노 (ICE)",
    price: 4500,
    image: "",
    description: "깊고 진한 풍미의 원두로 내린 시원한 아이스 아메리카노입니다.",
  },
  {
    id: 206,
    type: "drink",
    name: "생수",
    price: 2000,
    image: "",
    description: "가장 순수하고 깨끗한 프리미엄 생수입니다.",
  },

  // === 굿즈 (Goods) ===
  {
    id: 301,
    type: "goods",
    name: "영화 캐릭터 키링",
    price: 12000,
    image: "",
    description: "지금 가장 인기있는 영화의 주인공을 키링으로 만나보세요!",
  },
  {
    id: 302,
    type: "goods",
    name: "오리지널 영화 포스터",
    price: 15000,
    image: "",
    description: "소장 가치가 높은 오리지널 영화 포스터입니다. (A2 사이즈, 지관통 포함)",
  },
  {
    id: 303,
    type: "goods",
    name: "시그니처 렌티큘러 티켓",
    price: 8000,
    image: "",
    description: "보는 각도에 따라 이미지가 변하는 특별한 렌티큘러 티켓을 모아보세요.",
  },
  {
    id: 304,
    type: "goods",
    name: "무비 사운드트랙 LP",
    price: 45000,
    image: "",
    description: "영화의 감동을 그대로, 한정판으로 제작된 오리지널 사운드트랙 LP입니다.",
  },
  {
    id: 305,
    type: "goods",
    name: "캐릭터 피규어 (랜덤)",
    price: 18000,
    image: "",
    description: "어떤 캐릭터가 나올까? 두근거리는 마음으로 열어보는 랜덤 피규어 박스입니다.",
  },
  {
    id: 306,
    type: "goods",
    name: "영화 로고 뱃지 세트",
    price: 22000,
    image: "",
    description: "영화의 상징적인 로고와 아이템으로 구성된 고품질 뱃지 세트입니다.",
  },
  {
    id: 307,
    type: "goods",
    name: "컨셉 아트북",
    price: 32000,
    image: "",
    description: "영화의 세계관과 제작 과정을 엿볼 수 있는 아름다운 컨셉 아트북입니다.",
  },
];